# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Lesson.create(exercice: "OUI", translation: "YES", level: 1)
Lesson.create(exercice: "NON", translation: "NO", level: 1)
Lesson.create(exercice: "BIEN", translation: "NICE", level: 1)
Lesson.create(exercice: "AMI", translation: "FRIEND", level: 1)
Lesson.create(exercice: "STYLO", translation: "PEN", level: 1)
Lesson.create(exercice: "HIER", translation: "YESTURDAY", level: 1)
Lesson.create(exercice: "NUIT", translation: "NIGHT", level: 1)
Lesson.create(exercice: "JOUR", translation: "DAY", level: 1)
Lesson.create(exercice: "AVION", translation: "PLANE", level: 1)
Lesson.create(exercice: "NEZ", translation: "NOSE", level: 1)
Lesson.create(exercice: "DENTS", translation: "TEETH", level: 1)
Lesson.create(exercice: "DOIGTS", translation: "FINGERS", level: 1)
Lesson.create(exercice: "MANGER", translation: "TO EAT", level: 1)
Lesson.create(exercice: "FAIRE", translation: "TO DO", level: 1)
Lesson.create(exercice: "BROSSER", translation: "BRUSH", level: 1)
Lesson.create(exercice: "MONTER", translation: "CLIMB", level: 1)
Lesson.create(exercice: "LANCER", translation: " TO THROW", level: 1)
Lesson.create(exercice: "FRITES", translation: "FRIES", level: 1)
Lesson.create(exercice: "COURRIR", translation: "TO RUN", level: 1)
Lesson.create(exercice: "CHIEN", translation: "DOG", level: 1)
Lesson.create(exercice: "CHAT", translation: "CAT", level: 1)
Lesson.create(exercice: "POISSON", translation: "FISH", level: 1)
Lesson.create(exercice: "EAU", translation: "WATER", level: 1)
Lesson.create(exercice: "BOIRE", translation: "TO DRINK", level: 1)
Lesson.create(exercice: "SAUTER", translation: "TO JUMP", level: 1)
Lesson.create(exercice: "LUNDI", translation: "MONDAY", level: 1)
Lesson.create(exercice: "MARDI", translation: "TUESDAY", level: 1)
Lesson.create(exercice: "MERCREDI", translation: "WEDNESDAY", level: 1)
Lesson.create(exercice: "JEUDI", translation: "THURSDAY", level: 1)
Lesson.create(exercice: "VENDREDI", translation: "FRIDAY", level: 1)
Lesson.create(exercice: "SAMEDI", translation: "SATURDAY", level: 1)
Lesson.create(exercice: "DIMANCHE", translation: "SUNDAY", level: 1)




Lesson.create(exercice: "AU REVOIRS", translation: "BYE", level: 2)
Lesson.create(exercice: "AUJOURDHUI", translation: "TODAY", level: 2)
Lesson.create(exercice: "IL EST", translation: "HE IS", level: 2)
Lesson.create(exercice: "ILS SONT", translation: "THEY ARE", level: 2)
Lesson.create(exercice: "JE SAIS", translation: "I KNOW", level: 2)
Lesson.create(exercice: "TU SAIS", translation: "YOU KNOW", level: 2)
Lesson.create(exercice: "IL SAIT", translation: "HE KNOWS", level: 2)
Lesson.create(exercice: "JE SUIS", translation: "I AM", level: 2)
Lesson.create(exercice: "JE DANCE", translation: "I DANCE", level: 2)
Lesson.create(exercice: "JE MANGE", translation: "I EAT", level: 2)
Lesson.create(exercice: "TU JOUES", translation: "YOU PLAY", level: 2)
Lesson.create(exercice: "DEUX POISSONS", translation: "TWO FISHES", level: 2)
Lesson.create(exercice: "SON CHIEN", translation: "HIS DOG", level: 2)
Lesson.create(exercice: "JE RIGOLE", translation: "JUST KIDDING", level: 2)
Lesson.create(exercice: "TROP TARD", translation: "TOO LATE", level: 2)
Lesson.create(exercice: "HIER SOIR", translation: "LAST NIGHT", level: 2)
Lesson.create(exercice: "CE MATIN", translation: "THIS MORNING", level: 2)
Lesson.create(exercice: "MON PIED", translation: "MY FOOT", level: 2)
Lesson.create(exercice: "CE LUNDI", translation: "THIS MONDAY", level: 2)
Lesson.create(exercice: "LUI AUSSI", translation: "HIM TOO", level: 2)
Lesson.create(exercice: "MON PRENOM", translation: "MY FIRST NAME", level: 2)
Lesson.create(exercice: "MES VACANCES", translation: "MY VACATION", level: 2)
Lesson.create(exercice: "TON BALLON", translation: "YOUR BALL", level: 2)
Lesson.create(exercice: "SON FILS", translation: "HIS SON", level: 2)
Lesson.create(exercice: "CA FILLE", translation: "HIS DAUGHTER", level: 2)
Lesson.create(exercice: "MON PERE", translation: "MY DAD", level: 2)
Lesson.create(exercice: "MA MERE", translation: "MY MOM", level: 2)



Lesson.create(exercice: "JE VAIS BIEN", translation: "I AM GOOD", level: 3)
Lesson.create(exercice: "NOUS SAVONS", translation: "WE KNOW", level: 3)
Lesson.create(exercice: "MERCI BEAUCOUP", translation: "THANK YOU VERY MUCH", level: 3)
Lesson.create(exercice: "TU JOUE BIEN", translation: "YOU PLAYED WELL", level: 3)
Lesson.create(exercice: "JE MANGE DU PAIN", translation: "I EAT BREAD", level: 3)
Lesson.create(exercice: "MON DOIGT", translation: "MY FINGER", level: 3)
Lesson.create(exercice: "PARTIR EN VACANCE", translation: "GO ON VACATION", level: 3)
Lesson.create(exercice: "MES FILLES", translation: "MY DAUGHTER", level: 3)
Lesson.create(exercice: "MANGER DU POISSON", translation: "TO EAT FISH", level: 3)
Lesson.create(exercice: "JOUER AVEC MON CHAT", translation: "TO PLAY WITH MY CAT", level: 3)
Lesson.create(exercice: "MON PERE A DIT", translation: "MY DAD SAID", level: 3)
Lesson.create(exercice: "CE LUNDI", translation: "THIS MONDAY", level: 3)
Lesson.create(exercice: "EN VACANCE", translation: "ON VACATION", level: 3)
Lesson.create(exercice: "COURIR VITE", translation: "TO RUN FAST", level: 3)
Lesson.create(exercice: "FINIR MES DEVOIR", translation: "FINISHING MY HOMEWORK", level: 3)
Lesson.create(exercice: "DEUX OREILLES", translation: "TWO EARS", level: 3)
Lesson.create(exercice: "JOUER DEHORS", translation: "PLAY OUTSIDE", level: 3)
Lesson.create(exercice: "BALLON DE FOOT", translation: "SOCCER BALL", level: 3)
Lesson.create(exercice: "JUS DE POMME", translation: "APPLE JUICE", level: 3)
Lesson.create(exercice: "JE SUIS MALADE", translation: "I AM SICK", level: 3)
